### PR TITLE
fix route typo

### PR DESCRIPTION
**Pull request by tpeek**
Looks  like it was just a small typo. I also removed different login path- we already have that in Main.js, we don't need it in index.js.

### CODE REVIEW

**Comment by tpeek** [comment]
Well, this did work, but now it doesn't 🤷‍♂️

**Comment by tpeek** [comment]
Ok, now it works!

**Comment by justinhernandez** [comment]
@brauliojde thanks for the heads up. I will update my PR

**Comment by justinhernandez** [comment]
@brauliojde @tpeek let's go ahead and approve this PR and merge since it came in first then I will rebase and pull in these changes. It was nice coding with you guys today.

**Pull request merged**
